[build]
  publish = "/"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/reportes"
  to = "/modulo-reportes.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"